### ISSUE TITLE
Small keyboard of iPadOS makes Telegram very buggy

### ISSUE THREAD

**Issue by NightMachinary** [TelegramMessenger/Telegram-iOS#172] opened 2019-10-06 20:22 UTC
Try moving the small keyboard. It completely hides the open chat.
![BB07FDE1-CDBC-4F71-98F8-A810D2CA206D](https://user-images.githubusercontent.com/36224762/66275355-9be83100-e894-11e9-924c-930449baee01.png)

**Comment by laktyushin** [comment] 2019-10-07 04:17
Duplicate of #166

**Closed by laktyushin** 2019-10-07 04:17 UTC
