### ISSUE TITLE
Video from Android is blurred (sound works)

### ISSUE THREAD

**Issue by merttoka** [TelegramMessenger/Telegram-iOS#10] opened 2018-12-10 01:59 UTC
When I receive an `.mp4` footage from an Android phone, my iPhone cannot play that. The video shows a blurred version of the first frame and sound works as expected.

_iPhone specs (receiver):_ 
iPhone 7
iOS 12.1
Telegram version: 5.0.17

_Android specs (sender):_
LG G6
Android 8.0.0
Telegram version: 4.9.1

The same video works on the desktop version, and people with Android devices can play it. I also tried receiving the same footage on WhatsApp and it worked.

**Comment by incIined** [comment] 2018-12-10 04:19
https://t.me/tgiostests/20626

**Comment by basickarl** [comment] 2019-03-20 14:21
My friend is getting the same on her iOS device. So I can't send any shady videos to her anymore.

**Comment by furkantektas** [comment] 2019-05-28 23:12
I can confirm that this issue is still active after months. 
`iOS: 12.3, iPhone 7`
Sender:
`Android 9.0, OnePlus 5T`

**Comment by KevDoy** [comment] 2019-06-20 14:42
This is still a problem on iOS13 Beta and iPadOS as well.

**Comment by shivanraptor** [comment] 2019-06-21 02:06
> This is still a problem on iOS13 Beta and iPadOS as well.

As mentioned above, it's the formatting problem led by some Chinese-brand Android devices. Problem still exists in `release-5.7`.

**Comment by KevDoy** [comment] 2019-06-21 02:09
@shivanraptor it's not just from Chinese devices. Videos sent from Pixel devices and screen recordings from iPad suffer as well.

**Comment by shivanraptor** [comment] 2019-06-21 02:12
> @shivanraptor it's not just from Chinese devices. Videos sent from Pixel devices and screen recordings from iPad suffer as well.

Can you post the iPad screen recording file for investigation?

**Comment by KevDoy** [comment] 2019-06-21 02:35
> > @shivanraptor it's not just from Chinese devices. Videos sent from Pixel devices and screen recordings from iPad suffer as well.
> 
> Can you post the iPad screen recording file for investigation?

Apparently I misunderstood my friends who have iPhones. They are able to see the screen recordings from my iPad, just not videos from Pixel 3 and OnePlus 6T

**Comment by MarkHershey** [comment] 2019-07-04 08:08
Video shot by pixel 3a, sent by telegram(v5.8) on Google Pixel 3a (android 9) is shown blurred on telegram(v5.8.1) on iPhone & iPad(iOS 12.3.1) 
![IMAGE 2019-07-04 16:08:28](https://user-images.githubusercontent.com/25876605/60650057-f62cbc80-9e75-11e9-975f-18f3bcbb4a90.jpg)

**Comment by higginsbass** [comment] 2019-07-23 23:19
Still a problem on iOS with videos sent from Pixel 3a :-(

**Comment by KevDoy** [comment] 2019-07-25 16:00
Filed a bug report with in-app Volunteer Support.

**Comment by spacepluk** [comment] 2019-09-15 16:31
Sliding on the timeline shows thumbnails of the video. So it seems it can decode the video.

**Comment by laktyushin** [comment] 2019-09-15 20:46
The issue is in Android app's video encoding. The app developer told me he finally figured it out and both Android 10 and OnePlus issues will be fixed in the next Android app release. 

It will only fix the issue for new videos sent after the upcoming release. We are not planning to fix playback of old broken videos on iOS side as iPhones can't play them with hardware-based video decoding.

**Comment by apalayret** [comment] 2019-09-30 12:42
I encounter the same issue (I'm on Pixel phone) with users on IOS...

But someone try to get my video and reupload it, wich give the IOS's user the ability to read my video ! So the issue could be existing with actual videos

**Comment by CloudyMcFox** [comment] 2019-10-05 01:33
Fixed for me in latest update (version 5.12.0).

**Comment by laktyushin** [comment] 2019-10-05 16:05
People are reporting that it is fixed for new videos sent with TG Android 5.12 so I'm closing the issue.

**Closed by laktyushin** 2019-10-05 16:05 UTC

**Comment by VadVergasov** [comment] 2020-07-21 18:00
This issue appears on iPad 4 on the latest available version

**Comment by KevDoy** [comment] 2020-07-21 21:10
> This issue appears on iPad 4 on the latest available version

Which version of Telegram is on that iPad? It could be that the iPad 4, a now outdated system, is running an old version of Telegram with little hope of a fix coming.

**Comment by VadVergasov** [comment] 2020-07-22 06:24
It seems to be 6.2.1 and I've checked that when saving to gallery video is showing like unplayable (the gray screen with clit sign).
