### ISSUE TITLE
[Feature Request] System based dark/light theme selection

### ISSUE THREAD

**Issue by kharmadar** [TelegramMessenger/Telegram-iOS#192] opened 2019-11-02 06:35 UTC
Hi and thanks for the awesome apps.

The light/dark feature in the app is super great but it can be a little improved. It features all the light/dark auto adjustment features pretty well like the operating system. So if you want to have dar from sunset to sunrise it works just like the system, on light level, the same. But for those like me who wanna have things changed with the push of the dark/light button in the control center, Telegram still needs another step of manually shifting the appearance which when you keep changing the dark/light, becomes a bit frustrating. So can you add a new option which listens to the system setting and adjust for it in here:

![299F3D3D-E39A-4428-976A-27869026EAD1](https://user-images.githubusercontent.com/57100914/68067129-ed7ec100-fd57-11e9-89df-65d93a983d23.png)

Like for example; the iA Writer app:

![6220A9D5-6EF0-44BB-B3C4-9050D77D67A9](https://user-images.githubusercontent.com/57100914/68067152-36cf1080-fd58-11e9-806b-b92b625becd7.png)

**Comment by kharmadar** [comment] 2019-11-02 06:51
And you can access the light/dark interface settings from `UITraitCollection.current`

**Comment by laktyushin** [comment] 2019-11-02 07:44
Duplicate of #171.

**Closed by laktyushin** 2019-11-02 07:44 UTC
