### ISSUE TITLE
5.12 Release

### ISSUE THREAD

**Issue by LarsBoeckel** [TelegramMessenger/Telegram-iOS#207] opened 2019-12-04 12:48 UTC
We are still lacking the sources for Version 5.12

**Comment by Kylmakalle** [comment] 2019-12-04 13:19
Duplicate of #183

**Closed** 2019-12-04 15:41 UTC

**Comment by shivanraptor** [comment] 2020-01-03 06:20
Thanks @laktyushin . However, `release-5.13` lacks XCWorkspace file to build.
