### ISSUE TITLE
'opus/opus.h' file not found

### ISSUE THREAD

**Issue by XavierLost** [TelegramMessenger/Telegram-iOS#199] opened 2019-11-14 09:49 UTC
'opus/opus.h' file not found ,Is there a way to fix this? I tried many methods without compiling successfully.
![818B524D-69FA-43E2-8E7D-124BA9428EB4](https://user-images.githubusercontent.com/24632295/68845705-c84e6300-0706-11ea-8f9f-bdce284b199f.png)
#168 #21

**Comment by laktyushin** [comment] 2019-11-14 14:45
Duplicate of #168

**Closed by laktyushin** 2019-11-14 14:45 UTC
