### ISSUE TITLE
Telegram Messenger App version 8.8, 8.9 and 9.0 crash when opening a chat on iPad2,4 (iOS 9.3.5)

### ISSUE THREAD

**Issue by LeaHummer** [TelegramMessenger/Telegram-iOS#840] opened 2022-09-17 12:23 UTC
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Open a chat crashes App back to OS.

### Expected Behavior
The App should display a chat in the main area. 

### Actual Behavior
The App crashes and the iOS desktop is displayed.

### Steps to Reproduce
1. install version 8.8, 8.9 or 9.0 on iOS 9.3.5 (latest build for iPad2,4)
2. start Telegram Messenger App and attempt to open a chat by tapping the item in the left sidebar
3. witness fault as described, above

### Environment
**Device:** iPad

**iOS version**: 9.3.5

**App version:** 8.8, 8.9 and 9.0

**Comment by ali-fareed** [comment] 2022-09-20 08:09
Duplicate of https://github.com/TelegramMessenger/Telegram-iOS/issues/791

**Closed by ali-fareed** 2022-09-20 08:09 UTC
Labels: bug
