### ISSUE TITLE
APP_CONFIG_DATA

### ISSUE THREAD

**Issue by SpectreMz** [TelegramMessenger/Telegram-iOS#32] opened 2019-03-31 18:11 UTC
Can you help me with this?
 NSString *hex = @(APP_CONFIG_DATA); (Use of undeclared identifier 'APP_CONFIG_DATA')
thanks.

**Comment by shivanraptor** [comment] 2019-04-01 03:39
Duplicate of #28

**Closed** 2019-07-08 13:52 UTC
