### ISSUE TITLE
Telegram for iOS crashes when some users opens my channel

### ISSUE THREAD

**Issue by FedericoGB25** [TelegramMessenger/Telegram-iOS#139] opened 2019-08-30 23:09 UTC
Hello,
I have a channel where I post messages using @chelpbot and adding images preview using the Instant View testing link. (I sent my templates).

But recently, some users written me that their iOS Telegram app crashes when clicking my channel. With other channels this does not happen.

![ezgif-5-341aa4fe4104](https://user-images.githubusercontent.com/36126611/64055290-dc64d880-cb8b-11e9-8b9a-84066689837e.gif)

iOS Version: 13 Beta

Thanks for reading

**Comment by FedericoGB25** [comment] 2019-08-30 23:40
I noticed that the cause is strange chars in messages:
The message is this:

​📊 Molte volte, vediamo molti server coinvolti in un'unione che potrebbe portare benefici per entrambi oppure alla chiusura di entrambi.
E tu? Sei favorevole alle unioni tra servers?
#Polls #Servers #Unioni

┌ Sì  [15]
├ virus
├ Samuel
├ Super Damiano
├ Toxi10
├ ᗩᑎᗞᖇᗴᗩ
├ DrastZ_ 🔥
├ FEDERICOSCHI ~
├ Alex
├ Nele
├ wtfSpace Heaven
├ Tha Walife
├ peater parker
├ xBlsqSteel [+] 100
├ HYPERX
└ iTzCħrīBømbēr

┌ No  [40]
├ Manuh_ #ModernMcProject #McSecurity #ModernAlso
├ 𝕵3𝖈𝖐𝖊𝖓𝖉 [semi-off]
├ Mattia ~ 💕 [OFF FINO AL 27/08]
├ StivenFocs
├ 🐯 ImKingEz_ 🐯 #Bellish
├ ₱̖̪̉ ̦̽𝒪̮̲̑̌̌̃ͅ₩̫̼̙̇̑Ɇ͇̣ͪ̆̚Ɽ ̘̙̀ͧ̅ͤ͆_̪͌ͭ₩ͦ̆ͪ̒̈́̚𝒪̠̤̣͔̲̂̓Ⱡ͇̟̂͋ͮ̚₣
├ Čøňfïđəņćý
├ ᴢAʀᴛᴇᴍɪs | AʀᴋᴇᴜsCʀᴀғᴛ
├ Giulia
├ Giuseppe
├ xQuickGlare ᵖˡᵘᵍᶤᶰᶤᵗᵃˡᶤᵃ
├ OnlyFire | Java
├ Lino9999
├ Gabriele
├ ※ Aℓєѕѕισ. • アレッシオ 🌹 ~
├ 📦 CianoScatolo - PremiumPostsBot
├ Giuseppe
├ Peppe 😆
├ Anti-Corrupter | {Corrupter}•{æ and asd are legends}
├ ƭɦεɠαɱε૨૨૨
├ Shadow405
├ Edoardo
├ Francesco
├ Andrea | #AndreaLabs
├ 《𝑀𝒜》Peppe
├ RixterTV
├ 𝓯𝓮𝓭𝓮_𝟎𝟎𝟏 // Hioshi
├ Andrix  #Else #Bau
├ ᴢMᴀᴛᴛʏ₂₈ | 马蒂亚
├ Ξｄｄｙ
├ Kurama|Kyuubi
├ Davide Galilei
├ ‌‌‎ ‌‌‌‎WHiTeG0Dz_ ‌‌‎ ‌‌| [COMPLEANNO]
├ Burrascoso
├ ⚡WhiteDragon7⚡ - Founder ParadiseTemple [1,5K] Dev | 💰Account Seller💰 [YT] [DestinyWars - 0.3K]
├ αℓѕσƓAMƐR@MCTime:~# </b> #MCSecurity #Fedizia #BBONA #LilloGang
├ 𝙈𝙞𝙨𝙩𝙚𝙧𝙋𝙞𝙠𝙖
├ ⚡~zOxeey_ [#LeaveMeAloonneee]⚡
├ Nick_Gamer89 [In Vacanza]
└ FedericoGB25

Android users does not have this issue.

**Comment by Neurotoxin001** [comment] 2019-08-31 06:28
> ├ ₱̖̪̉ ̦̽𝒪̮̲̑̌̌̃ͅ₩̫̼̙̇̑Ɇ͇̣ͪ̆̚Ɽ ̘̙̀ͧ̅ͤ͆_̪͌ͭ₩ͦ̆ͪ̒̈́̚𝒪̠̤̣͔̲̂̓Ⱡ͇̟̂͋ͮ̚₣

Tested on 12.4.1 / 5.10 - no crash.

**Comment by FedericoGB25** [comment] 2019-08-31 11:51
All my iOS users crashes seeing these chars only in Telegram. WhatsApp does not crash. Same iOS version and same Chars

**Comment by Neurotoxin001** [comment] 2019-08-31 11:52
Can you create new empty channel with only these chars and give link here?

**Comment by FedericoGB25** [comment] 2019-08-31 11:55
Telegram app crashes only when I forward a message with these chars.
Testing link: https://t.me/joinchat/AAAAAEdOz7FxZromN4JxRw

**Comment by Neurotoxin001** [comment] 2019-08-31 11:56
Maybe it's iOS 13 issue? 12.4.1 still ok.

![image](https://user-images.githubusercontent.com/39812401/64063640-7f0a6f00-cbff-11e9-91d4-0e5568d50f05.png)

**Comment by Neurotoxin001** [comment] 2019-08-31 14:38
Some my friends with iOS 13 confirms crash.

**Comment by Neurotoxin001** [comment] 2019-08-31 21:35
On iOS 12.4.0 crashes too

**Comment by ethylmorphine** [comment] 2019-09-01 06:46
iOS 12.4.1, confirm crash.

**Comment by shivanraptor** [comment] 2019-09-02 03:01
On iOS 12.4.1, App release v5.10, iPhone XR (physical device), no crash when entering the channel, forward the message, receive the forwarded message. Zero error or warning in Xcode console.

Only the following logs are recorded (already set `OS_ACTIVITY_MODE` to `default`) when copying the string using iOS's default Copy text function & Forward message > Copy Link:

```
2019-09-02 10:59:24.406265+0800 Telegram[15116:1900520] Returning local object of class NSString
2019-09-02 10:59:33.959034+0800 Telegram[15116:1901743] PBItemCollectionServicer connection disconnected.
```

These are not fatal errors, just information. Other actions apparently have no debug information at all.

**Comment by laktyushin** [comment] 2019-09-05 22:26
Could you check it on 5.11 please? It couldn't reproduce it on any of my devices.

**Comment by Neurotoxin001** [comment] 2019-09-05 23:16
iOS 12.4.1 / tg 5.11
no crash

**Comment by ethylmorphine** [comment] 2019-09-06 12:54
5.11, 12.4.1, iPhone 7, no crash as well.

**Comment by laktyushin** [comment] 2019-09-06 14:44
Good, so I'm closing the issue.

**Closed by laktyushin** 2019-09-06 14:44 UTC
