### ISSUE TITLE
Context menu issues in Slide Over

### ISSUE THREAD

**Issue by artazol** [TelegramMessenger/Telegram-iOS#92] opened 2019-07-18 17:15 UTC
![60398122-7e9d1b80-9b5d-11e9-8190-8fbbc2435587](https://user-images.githubusercontent.com/25721016/61477804-c662d600-a998-11e9-983f-2ede033aca65.png)
This issue persists from 5.0.2 to 5.10 in TestFlight

**Comment by laktyushin** [comment] 2019-07-18 17:17
Duplicate of #78

**Closed by laktyushin** 2019-07-18 17:17 UTC
