### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by nanirocks125** [TelegramMessenger/Telegram-iOS#82] opened 2019-07-05 11:59 UTC
**No such module 'SwiftSignalKit' in TelegramAudio Framework**

It is already present in the Linked Frameworks and Libraries
![Screenshot 2019-07-05 at 5 28 57 PM](https://user-images.githubusercontent.com/25024660/60721077-64db4a00-9f4a-11e9-841f-cf5602ca69d8.png)

**Comment by shivanraptor** [comment] 2019-07-05 12:01
Duplicate of #76

**Comment by nanirocks125** [comment] 2019-07-05 12:49
Thank you @shivanraptor 
Kindly update the Read.Me file ( Telegram-iOS-Fork to  Telegram-iOS-AppStoreLLC )

**Comment by shivanraptor** [comment] 2019-07-09 03:41
You still need to use `Telegram-iOS-Fork` target.

**Comment by DukeHuang** [comment] 2019-07-20 02:13
I used `Telegram-iOS-Fork` target, the same wrong with @nanirocks125 .Then I changed to the 
`Telegram-iOS-AppStroeLLC` target, success compile!

**Comment by XavierLost** [comment] 2019-08-02 07:24
I changed to the Telegram-iOS-AppStroeLLC , prompt " The bundle identifier of the application could not be determined"

**Comment by RodPrestes** [comment] 2019-09-19 06:40
It appears that PR #116 has been a little out of sync.
Tried applying its changes on latest master but had no luck building.
PR branch builds fine but lacks new features.

**Closed** 2020-07-26 10:08 UTC
