### ISSUE TITLE
one way audio - Compatibility with Libtgvoip - lost \ broken 2.4.4 voip instance

### ISSUE THREAD

**Issue by oksakhartman** [TelegramMessenger/Telegram-iOS#1030] opened 2023-02-26 17:10 UTC
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
one way audio - Compatibility with Libtgvoip - lost \ broken 2.4.4 voip instance

### Expected Behavior
calls from libtgvoip - any client works good till 2023

### Actual Behavior
calls from libtgvoip broken - only on ios - seems it`s ios client issue - maybe need add flag TGVOIP_NO_DSP and rebuild client?

### Steps to Reproduce
1. get any libtgvoip client  2.4.4 - easy way is use android 4 - it will automaticly use only libtgvoip for call
2. call any modern ios device on telegram from libtgvoip 
3. call will coneect but audio will not work on both side

### Environment
**Device:**  any ios device

**iOS version**:  latest ios - but it does not matter - same issue on other versions

**App version: latest ios

**Comment by oksakhartman** [comment] 2023-02-26 18:41
in 

Telegram-iOS/submodules/TgVoip/

maybe we need use 
this libtgvoip - latest
https://github.com/telegramdesktop/libtgvoip/tree/tdesktop


in https://github.com/TelegramMessenger/Telegram-iOS/blob/master/submodules/TgVoip/BUILD

"-DTGVOIP_USE_CUSTOM_CRYPTO", - maybe we need remove it?

and libtgvoip dont need old webrtc files - it`s confligcting with new one - maybe remove it?

**Comment by ali-fareed** [comment] 2023-02-26 20:04
2.4.4 and earlier versions have been deprecated. Telegram X is in the process of moving to the updated code.

**Closed by ali-fareed** 2023-02-26 20:04 UTC
Labels: bug

**Comment by oksakhartman** [comment] 2023-02-26 20:15
> 2.4.4 and earlier versions have been deprecated. Telegram X is in the process of moving to the updated code.

Are you seriously?

All other official tg apps Windows \ Mac \ Linux \ Android \ FreeBSD - work with Libtgvoip

Yes, there can be 1 flag to remove and everything will work

Why can't you recognize the fact that the problem is in the iOS application?

**Comment by ali-fareed** [comment] 2023-02-26 20:25
No, these flags are not going to make it work.

Is there a specific reason you would like to use tgvoip 2.4.4?

**Comment by oksakhartman** [comment] 2023-02-26 20:36
> No, these flags are not going to make it work.

we can just get latest libtgvoip from desktop and use it
https://github.com/telegramdesktop/libtgvoip/tree/tdesktop

and we can set same build flags as on android or desktop  \ we can also remobe all webrt links from libtgvoip - it conflicts and same issue was in andoid last year

>Is there a specific reason you would like to use tgvoip 2.4.4?

https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/messenger/voip/Instance.java

all android phones up to 4 use libtgvoip (at least that's how it used to be)

all tg clients have code that supports it

there are still a huge number of third-party clients that use it from telegram x to many others

and until February it also worked in ios - what happened there in February that broke the work with libtgvoip

it seemed to me that if tg officially broke its support - they would turn off the server part and remove its code from all clients

**Comment by ali-fareed** [comment] 2023-02-26 20:43
> what happened there in February that broke the work with libtgvoip

It was modernized audio IO handling. Tgvoip would need a separate implementation, which is not worth the time considering it’s not widely used.

> remove its code from all clients

That’s the plan.

**Comment by oksakhartman** [comment] 2023-02-26 20:47
> It was modernized audio IO handling. Tgvoip would need a separate implementation, which is not worth the time considering it’s not widely used.

that is just the time

last year there was a similar problem on android, but it was not audio IO handling

and the correct solution would be to rewrite clients  - not libtgvoip 




> That’s the plan.

that is, this time for sure everything - official support stop

**Comment by ali-fareed** [comment] 2023-02-26 20:55
This time it most definitely is the IO.

Telegram for iOS is not going to support 2.4.4 anymore. At some point in the future other apps may drop the support as well.

**Comment by oksakhartman** [comment] 2023-03-11 18:25
hi @ali-fareed 

based of this

https://github.com/Infactum/tg2sip/issues/73#issuecomment-1464948609

seems new ios client can work with libtgvoip

but not stable  not 10 from 10)

what do you think it might look like an fixable bug

it still works sometimes and is it possible if you use the latest libtgvoip - will it work stably?)

**Comment by ali-fareed** [comment] 2023-03-12 06:40
The linked thread is unrelated to this issue. The current VoIP-related code is tightly coupled with an iOS-specific WebRTC audio device management setup. It is possible to patch things and make it work with libtgvoip, but there is no use for it anymore as all official clients have moved to tgcalls.

**Comment by multi** [comment] 2023-03-12 08:00
@ali-fareed Hey 👋 

>The current VoIP-related code is tightly coupled with an iOS-specific WebRTC audio device management setup.

Can you be more specific, please? 

>It is possible to patch things and make it work with libtgvoip

Can you give any hints, what to look for? 

>but there is no use for it anymore as all official clients have moved to tgcalls

That's fine. But then, why some of the calls have audio (libtgvoip <-> ios tg)? See the tests that I've made [here](https://github.com/Infactum/tg2sip/issues/73#issuecomment-1464948609)

Not sure, but I'm suspecting that, it's something around the timings of the events or else in that direction?

Another thing that I noticed - if I mute the mic on the ios client - packet loss recovers and goes back to 0%, when i unmute the mic, packet loss goes up again... (signal bar count drops from 4 to 0)

**Comment by ali-fareed** [comment] 2023-03-12 08:47
> Can you be more specific, please?

Telegram was designed to support interchangeable VoIP implementations. The workflow is as follows:

- exchange encryption key material + supported protocol versions
- run key agreement + deterministically decide on the shared protocol version
- instantiate the selected protocol implementation
- run the selected implementation

That is, until the step 3 the application does not know which implementation ("library") is going to be used.

Before we reach that stage, the application needs to play back some sound (mainly, the "connecting", "busy", and similar tones). At least on iOS, the "libraries" directly call into low-level OS audio APIs. Interleaving the tone and the actual call audio I/O causes various problems on iOS. It was fixed by instantiating the iOS-specific WebRTC audio processing code from the rest of the call code, and running it before we know which implementation to use. After reaching the implementation initialalization stage, the application simply connects the running audio processing part to the newly initialized code.

> Can you give any hints, what to look for?

It all starts with `AudioDevice.create()`.

> why some of the calls have audio

Probably because the audio setup accidentally happens to be in a appropriate state.

**Comment by multi** [comment] 2023-03-12 10:25
@ali-fareed thanks for the comprehensive explanation, it helps a bit 😄 

>Probably because the audio setup accidentally happens to be in an appropriate state.

If you know more about that "magic" state, I'll be glad if you share how to get it in libtgvoip :) Or maybe, it will be easier to re-implement tg2sip using tgcalls instead of libtgvoip 🤔

**Comment by ali-fareed** [comment] 2023-03-12 10:30
@multi it is recommended to move to tgcalls. The now-default protocol (8.0.0) is compatible with standard WebRTC, which should make it way easier to support in third-party software.

**Comment by multi** [comment] 2023-03-12 10:37
@ali-fareed I see. If you have some insight and time, could you look at tg2sip/libtgvoip audio i/o implementation and give some hints what could be problematic? Thanks in advance!

**Comment by oksakhartman** [comment] 2023-03-12 13:48
> I see. If you have some insight and time, could you look at tg2sip/libtgvoip audio i/o implementation [1](https://github.com/Infactum/tg2sip/blob/master/libtgvoip/audio/SoftwareAudioInput.cpp) [2](https://github.com/Infactum/tg2sip/blob/master/libtgvoip/audio/SoftwareAudioOutput.cpp) and give some hints what could be problematic? Thanks in advance!

I don't think this will help

libtgvoip - standardized
and the problem only occurs in the ios client

need to fix it and not something else

but as the developers have already written above - they have something to do besides this

**Comment by oksakhartman** [comment] 2023-03-12 13:49
> The now-default protocol (8.0.0)

maybe you have any information how long the first version of tgcalls which is **2.7.7** will survive?
for now  -  it works great

**Comment by ali-fareed** [comment] 2023-03-12 14:10
@multi I will have to agree with @oksakhartman on this one — the libtgvoip itself is fine, the issue is with the upgraded iOS audio I/O. I don't think it would take too much time to fix it, but as I explained earlier, there isn't much sense to to so.

@oksakhartman 2.7.7 can be safely dropped now. 5.0.0 had been the baseline version for a while, before the server switched to 8.0.0.

**Comment by oksakhartman** [comment] 2023-03-12 14:43
> 2.7.7 can be safely dropped now. 5.0.0 had been the baseline version for a while, before the server switched to 8.0.0.

thanks 5.0.0 works too  \ will try test 8.0.0
