### ISSUE TITLE
Invalid Cert File

### ISSUE THREAD

**Issue by twisturn** [TelegramMessenger/Telegram-iOS#128] opened 2019-08-21 07:26 UTC
Invalid Cert File
![1566372347738](https://user-images.githubusercontent.com/17715937/63411419-16193f00-c428-11e9-9a0f-f058d4cb9a7c.jpg)

**Comment by shivanraptor** [comment] 2019-08-21 08:53
Duplicate of #29. Follow the command of the first comment.

**Comment by twisturn** [comment] 2019-08-21 09:25
@shivanraptor I changed the App api_id and App api_hash, but I didn't get the push message

**Comment by shivanraptor** [comment] 2019-08-21 09:35
As I mentioned, notification doesn't work. See #88

**Comment by twisturn** [comment] 2019-08-21 09:43
@shivanraptor I still don't know how to modify it

**Comment by twisturn** [comment] 2019-08-21 10:27
@shivanraptor My version is 5.5-Fork

**Comment by laktyushin** [comment] 2019-08-22 00:01
Duplicate of #29

**Closed by laktyushin** 2019-08-22 00:01 UTC

**Comment by twisturn** [comment] 2019-08-22 10:16
I completed all the operations but did not receive the notification
