### ISSUE TITLE
High battery usage 

### ISSUE THREAD

**Issue by houndlord** [TelegramMessenger/Telegram-iOS#815] opened 2022-07-26 09:20 UTC
Since last update (8.8.3) I experiencing huge energy consumption even with disabled background activity. 
IOS 15.5 on iPhone SE (2020).

I also started experiencing heating but not sure if it's correlated to the case.

**Comment by ali-fareed** [comment] 2022-07-26 11:55
Duplicate of https://github.com/TelegramMessenger/Telegram-iOS/issues/81

**Closed by ali-fareed** 2022-07-26 11:55 UTC
