### ISSUE TITLE
Invite to Group via Link - Crashes app

### ISSUE THREAD

**Issue by laurinkeithdavis** [TelegramMessenger/Telegram-iOS#787] opened 2022-06-19 10:49 UTC
First, complete the checklist by replacing the empty checkboxes [] with checked ones [x]. -->

### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Telegram app on iOS is crashing. Every time I click on invite members by link, app exits.

### Expected Behavior
Takes me a to the invite by link page. 

### Actual Behavior
App exits (crashes)

### Steps to Reproduce
1. Select any group
2. Click the group icon
3. Click Add Members
4. Click Invite to Group via Link

### Screenshots and Videos 
![image](https://user-images.githubusercontent.com/75857/174477206-f5981cb8-6337-4198-96e0-2d56ed8649f9.jpeg)

### Environment
**Device:** `iPhone 12 Pro Max`

**iOS version**: `15.5`

**App version:** `8.7.1`

**Comment by ali-fareed** [comment] 2022-06-26 16:03
The issue is fixed in 8.8.

**Closed by ali-fareed** 2022-06-26 16:03 UTC
Labels: bug
