### ISSUE TITLE
No such module 'MtProtoKitDynamic'

### ISSUE THREAD

**Issue by twisturn** [TelegramMessenger/Telegram-iOS#121] opened 2019-08-16 11:40 UTC
No such module 'MtProtoKitDynamic'

**Comment by shivanraptor** [comment] 2019-08-19 02:02
By creating a configuration named "DebugFork" in all projects (by duplicating "DebugAppStoreLLC"), the workspace can be built without errors. 

Duplicate of #76

**Closed** 2019-09-05 22:36 UTC
